### ISSUE TITLE
CockroachDB operator

### ISSUE THREAD

**Issue by annismckenzie** [k8sdb/operator#107]
Has anyone started on a CockroachDB operator yet? Pretty new to this whole k8s ecosystem so I don't have anything specific to ask. If this is a bad format and I should come back when I have something tangible, feel free to just close this issue. :)

**Comment by tamalsaha** [comment]
Welcome @annismckenzie ! We have not started anything yet. If you would like to start that we are happy to work to you.

**Comment by annismckenzie** [comment]
Thank you! I'll report back when I have something.

**Comment by tamalsaha** [comment]
Great!.

**Comment by tamalsaha** [comment]
@annismckenzie , I wonder if you made any progress on this? We now have a skeleton project to start writing new operators for additional databases. https://github.com/k8sdb/xdb

**Comment by annismckenzie** [comment]
Sadly, I haven't made any progress. I thought I'd get to finally play around with k8s but that hasn't happened yet. Thanks for the pointer to the skeleton project but feel free to close this issue for now because it's gonna be 2018 before I see myself in the position to consider picking this up again.
