### ISSUE TITLE
Check recovery success in DeletedDatabaseController

### ISSUE THREAD

**Issue by TamalSaha** [k8sdb/operator#14]
_From @aerokite on May 19, 2017 10:12_

Now individual database controllers are responsible for deleting DDB after recovered. 

If it encounters any error before deleting DDB, it causes problem, 
So, DDB remains in Recovering phase forever.

Probable solution:
Let DeletedDatabaseController to check recovery status. 
DDB controller will check for recovered database status. 

Individual database controller will implement that interface method.

_Copied from original issue: k8sdb/apimachinery#83_

**Comment by aerokite** [comment]
Issue Fixed.

While resuming a paused database, delete DormantDatabase object first.
Then create Original Database object.
