### ISSUE TITLE
Support DatabaseSnapshot

### ISSUE THREAD

**Issue by tamalsaha** [k8sdb/operator#4]
_From @TamalSaha on March 13, 2017 8:28_

# Goal: 
Port our grpc api to TPR based version: https://github.com/appscode/api/blob/ad5ff4c7690a95b53b682da388f164504f34fd14/db/v1beta1/snapshot.proto

# Design:
- Create a new TPR called `DatabseSnapshot`. This will work on any type of k8sdb. The object will have all the info necessary for taking snapshot.
  - DB reference
  - Bucket location, secrets for connection, etc. 
- Operator for each db will watch for `DatabseSnapshot` create events with matching label (eg, `k8sdb.com/type: postgres`).

User can manually create the `DatabseSnapshot` object to take one-of snapshots.

## Scheduled Snapshots
Each DB TPR will have fields for snapshot schedule and necessary info (bucket name, etc). If that field is set, operator for that Db type will create a Kubernetes CronJob using a `k8sdb-snapshotter` docker image. The `snapshotter` process lives in this repo. It creates a `DatabaseSnapshot` object everytime the cron job is scheduled. The actual process of snapshotting is done by the individual operators.

_Copied from original issue: k8sdb/apimachinery#1_

**Comment by TamalSaha** [comment]
@aerokite I think we should avoid using Kube's CronJob for now. It is still in alpha. And we are not going to use any alpha feature, given our past experience. So, we have do the cron part ourselves using robfig cron.

Kube's plan for CronJOb: https://github.com/kubernetes/kubernetes/issues/41039

**Comment by tamalsaha** [comment]
This issue was moved to kubedb/project#60
