### ISSUE TITLE
Support database initialization

### ISSUE THREAD

**Issue by tamalsaha** [k8sdb/operator#6]
_From @aerokite on April 7, 2017 9:30_

We can support database initialization when creating a new one. 

Support two different way to initialize database:
1. Initialize from DatabaseSnapshot
2. Initialize by running script

```
type InitSpec struct {
	*ScriptSource   `json:",inline,omitempty"`
	*SnapshotSource `json:",inline,omitempty"`
}

type ScriptSource struct {
	ScriptPath       string `json:"scriptPath,omitempty"`
	api.VolumeSource `json:",inline,omitempty"`
}

type SnapshotSource struct {
	namespace string `json:"namespace,omitempty"`
	name      string `json:"name,omitempty"`
}
```

`ScriptSource` can be used while creating database by running script. 
For example,
In Postgres, we can run script to initialize database with some configuration or data.

And ,

`SnapshotSource` can be used to restore from existing backup data.
In this case, when new database is ready, we can run a job that will restore snapshot in this database.

_Copied from original issue: k8sdb/apimachinery#16_

**Comment by TamalSaha** [comment]
cc: @ashiquzzaman33 need to update v1beta2 api once this in implemented. @aerokite co-ordinate with him.
