### ISSUE TITLE
Recover database from DeletedDatabase

### ISSUE THREAD

**Issue by tamalsaha** [k8sdb/operator#7]
_From @aerokite on April 7, 2017 9:36_

We can add another field name `Recover` in `DeletedDatabaseSpec`.

```
type DeletedDatabaseSpec struct {
	AuthSecret *api.SecretVolumeSource `json:"authSecret,omitempty"`
	Destroy bool `json:"destroy,omitempty"`
        Recover bool `json:"recover,omitempty"`
}
```

When `DeletedDatabase` instance will be updated with `recover` field `true`, a new Database TPR instance will be created with existing `PersistentVolume` and `Secret`. 

We can store Database TPR spec in annotation for recover process.

_Copied from original issue: k8sdb/apimachinery#17_

**Comment by TamalSaha** [comment]
cc: @ashiquzzaman33 need to update v1beta2 api once this in implemented. @aerokite co-ordinate with him.
